robot.py, wheel_of_fortune/wheel.py
A simple refactor of the current colour-wheel code into a component, just as it is, warts and all. Further work should use this as a base.
=> Refactor Wheel Of Fortune code into a subcomponent

.vscode/launch.json, .vscode/tasks.json
Just a copy-paste from last year.
=> Add VS Code run configurations

components/shooter.py, robot.py
Changed the Shooter loading_piston to a regular single solenoid.
=> Updated shooter DoubleSolenoid to Solenoid

components/turret.py, robot.py
This just seeks to align the turret to the hall-effect sensor on the centre line of the turret.
DO NOT MERGE YET, as it will spam the log. It looks good on the simulator, but we want to keep the logging until we see it work on the real turret.
=> Initial turret code

components/indexer.py, controllers/shooter.py, robot.py
Changed indexer code to comply with new architecture requirements. The majority of the indexer code has been moved to components/indexer.py, and the four methods required by the architecture doc have been added. Also, a third limit switch and motor have been added for the upcoming prototype.
=> Improved indexer code

components/turret.py, robot.py
Finds just the central hall-effect sensor at enable time, then uses the POV hat on Joystick 3 to slew approximately 20 degrees every time the hat is pushed left or right.
Issues:
The initial alignment to the hall-effect sensor overshoots.
The joystick control is purely for testing. We need to figure out how the turret will be controlled.
=> First working turret code

components/shooter.py, controllers/shooter.py, robot.py
This requires turret and vision code before it will work properly but should otherwise be ready.
=> Refactor shooter component and controller

components/chassis.py, components/hang.py, robot.py, utilities/scale_value.py
hang.py has no actual code, only stub functions to conform to the architecture doc. Chassis code is tested on the drive base and works fine.
=> Added chassis code and hang stub code. 

components/turret.py, robot.py
Commented out unused indexes.
Moved declaration of motor to robot.py, per magicbot, for consistency.
Cleaned up extraneous whitespace.
Added some more comments.
=> Small turret tweaks

robot.py
Hopefully people can respect this sorting so we don't keep getting merge
conflicts.
=> Sort and group robot.py

components/turret.py, robot.py
Change small gear from 12 teeth to 18.
Centre index is now on port 1 instead of 0
All indexes present but commented out, and wrapped in a function.
=> Update for new turret, and some refactoring

components/shooter.py, components/vision.py, controllers/shooter.py
Should help to reduce the oscillation of the turret under vision fluctuations
=> Update for new shooter and controller side changes for turret

components/indexer.py, components/shooter.py, components/turret.py, controllers/shooter.py
Unify component is_ready() calls
Add stub code to make turret scan when vision cannot find target
=> Improve shooter control

components/shooter.py, components/turret.py, controllers/shooter.py
=> Tune turret PID and fix some minor issues in shooter code

components/indexer.py, components/shooter.py, controllers/shooter.py, robot.py
This is still in development and will need further testing before being merged
=> ShooterController refactor

.vscode/settings.json, components/shooter.py, components/turret.py, controllers/shooter.py, robot.py
update_LED function moved to shooter controller
missing vision function
=> Add status LEDs

components/hang.py, components/turret.py, robot.py
note that hang controls are commented out until the mechanism is completed mechanically
=> populated hang component and cleaned code

components/vision.py
added a function to the vision component to check the status of vision for the leds
=> Vision ready check

components/turret.py, robot.py
Now waits for slewing to finish correctly, per CTRE's recommendation.
Iniital state is IDLE, and is_ready is defined to be IDLE, which is set by slewing and indexing when done.
Restored IO 0 as input for center hall-effect sensor.
Removed spurious code
=> Tweaked turret code

components/turret.py, controllers/shooter.py
Make the turret slew use the Talon position control mode
Update absolute azimuth when passing an index
Rely on controller to determine when to find an index (if at all)
In future we might want to investigate MotionMagic on the Talon to get smoother slewing.
=> Turret and turret control

requirements.txt
Allows selecting autonomous modes again.
Also fixes LiveWindow not being enabled in test mode.
=> Bump robotpy-wpilib-utilities to 2020.1.0

components/turret.py
Temporarily set to +- 45 degrees for debugging.
=> Add limits to prevent turret damage

components/turret.py
=> fix undefined check of target position in test mode

controllers/shooter.py
LED strips now display vision status;
Green is vision target && turret ready
Orange is vision target && !turret ready 
Red is no vision target 
Shooter LED strip is also using is_ready() instead of is_at_speed() now.
=> Make LED strips display vision status

components/indexer.py, robot.py
Added extra motors and switches. Added doubling for the indexer motor. Added support for ready_piston. Also fixed turret error by setting the initial state to idle.
=> Improved indexer code.

components/turret.py, robot.py
Fixes turret motion:
* indexing
* slewing
* scanning
=> Motionmagic

components/turret.py, robot.py
Also make the hall-effect sensor width test not happen when slewing manually
=> Reverse turret motor to match robot coordinate system

components/turret.py, robot.py
=> Extend hall-effect-sensor-width finding to use scan

components/indexer.py
Get power cells travelling along indexer and into the injector!!
=> Indexer injector interfacing

components/chassis.py, controllers/shooter.py, requirements.txt, robot.py
Still need to tune the PID gains.
=> Use velocity control on the drivetrain

components/turret.py
All rotations are in encoder counts to the extent possible.
=> Replace all real-time floating-point calcs with integer arithmetic

robot.py
The shooter controller should not read data from vision that lags by an
entire control loop iteration.
=> Run vision execute before controllers

utilities/git.py
Also removed redundant else to make pylint happy.
=> add --broken to git command so it fails gracefully

robot.py
fix a missed check from indexer refactor
=> fix indexer in test mode

components/vision.py
Also corrected the other None comparison.
=> fix target_in_sight None exception

components/indexer.py, robot.py
added the shooter to test mode for flywheel feedback. moved indexer speeds to prevent crash in test mode
=> shooter in test mode

components/chassis.py
The recommendation seems to be to divide the gains from LQR by ~10 for motor controller onboard velocity PID loops due to filtering.
This also fixes the feedforward gain to be in the correct units.
=> Make chassis PIDF gains more sensible

components/turret.py, components/vision.py, controllers/shooter.py, robot.py
Account for latency in vision by keeping a record of where we were when the image was processed and accounting for turret movement since.
=> Backtracking vision

components/led_screen.py, components/shooter.py, controllers/shooter.py, robot.py
What it says on the tin.
The methods in shooter.py were just delegating, with the real smarts in the controller.
=> Make the LED screen a component

components/shooter.py, robot.py
Awaiting characterisation and testing
=> refactor shooter component to use falcons

components/indexer.py
This restores erroneously removed functionality.
=> Feed ball into injector iff piston is retracted

components/indexer.py, components/shooter.py, components/turret.py, controllers/shooter.py, robot.py
Replace the ghetto state-machine and fix some state transitions
=> Use magicbot state-machine for ShooterController

components/turret.py
This is taken care of by the controller
=> Remove indexing scan

components/shooter.py, controllers/shooter.py
This also fixes some bugs in #47 that slipped through
=> Shooter tuning

components/chassis.py
These were calculated by the frc-characterization toolsuite.
=> Update chassis PID/feedforward gains

components/indexer.py, robot.py
Disable shimmy in auto
Shimmy speed and frequency increased
=> Treat intake as first indexer motor

.github/workflows/check.yml, requirements-test.txt, tests/test_constrain_angle.py
Also run these utility tests in CI.
=> Add constrain_angle test

components/chassis.py, components/target_estimator.py, components/turret.py, controllers/shooter.py, robot.py
In addition to merging in James' PR, this ensures that turnarounds aren't interrupted, widens the scan back to 90 degrees on each side, and starts scans downrange.
Marking as draft until we can test it thoroughly.
=> Merge estimator and tweak turret

components/indexer.py, components/shooter.py, components/turret.py, controllers/shooter.py, robot.py
First pass at driver controls
* Add co-driver gamepad
* Turret disable
* Ball eject through intake
=> Driver controls

components/hang.py, components/indexer.py
This will allow for fine-tuning of these mechanisms without constantly deploying code.
=> Make hang and indexer speeds and state tunable

components/indexer.py
intake_lowered is a tunable now, so this is unnecessary.
=> Remove redundant is_intake_lowered feedback

components/indexer.py, robot.py
Motors should not run if there is no ball available below them to carry up.
=> Run balls up the indexer when not intaking

components/chassis.py
=> Make code not crash

components/turret.py
Turret no longer ignores commands after 270 degrees of a turnaround.
=> Add turnaround patch for robot turning 

components/chassis.py, components/target_estimator.py, components/vision.py
The latest update to black improves handling of trailing commas, among other things.  This PR makes the latest version of black happy.
=> Reformat for black 20.8b1

utilities/git.py
--broken also implies --dirty it seems.
=> Print git branch along with commit

components/shooter.py, components/turret.py, robot.py
Fix the shooter disable to actually work and make both of them compliant with our standard of not directly changing variables in other classes.
=> Fix disable of turret and shooter

robot.py
The range finder should be read before the target estimator runs.
=> Fix ordering of range_finder

components/indexer.py, components/shooter.py
I kept getting confused when reading most of this code, so I'm sure others reading this would be at least just as confused.  Hopefully this makes things a lot clearer.
This PR should be reviewed commit by commit.
=> Clarify the indexer code

components/indexer.py, robot.py
i put in on the co drivers b button for now
=> Added intake reversing

.github/workflows/check.yml, components/target_estimator.py, controllers/shooter.py, robot.py
when x is held on the co drivers gamepad they can move the turret with the left stick
it still uses the lidar to set the range as usual
=> Manual turret
